package moduloinscripcion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import BD.ConexionBD;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 * @author Samuel
 */
public class ImprimirRecibo extends javax.swing.JDialog implements Printable{

    ConexionBD con=new ConexionBD();
Connection cn = con.conectar();
String Usuario;
    public ImprimirRecibo(java.awt.Frame parent, boolean modal, String usuario) {
        
        super(parent, modal);
        initComponents();
        Usuario=usuario;
        llenarrecibo();
        try {
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(this);
            job.printDialog();
            job.print();
            this.dispose();
        } catch (Exception e) {
        }
    }

    private ImprimirRecibo(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String obtenerinscripcion()
    {
        String consulta="SELECT max(id_inscipcion) FROM con_inscripciones";
        String IdInscripcion="";
       try
        {           
            Statement st =  cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);              
            while(rs.next())  //while simple      
            { 
             IdInscripcion=rs.getString(1);        
            }                                
        }
        catch(Exception ex) {        
         JOptionPane.showMessageDialog(null, "Error al obtener la inscripcion" + ex);
        }
       return IdInscripcion;
    }
    
    public void llenarrecibo()
    {
        String IdInscripcion=obtenerinscripcion();
        String consulta="Select A.Nombre, A.Carne, E.Precio, I.Correlativo, I.no_asiento, I.no_bus from con_alumnos A inner join con_inscripciones I on I.id_alumno=A.Id_Alumno inner join con_eventos E on I.id_evento=E.Id_evento where I.Id_Inscipcion="+IdInscripcion;       
       try
        {           
            Statement st =  cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);              
            while(rs.next())  //while simple      
            { 
             labelnombre.setText(rs.getString(1));        
             labelcarne.setText(rs.getString(2));
             labelprecio.setText(rs.getString(3));
             labelfirma.setText(rs.getString(4));
             labelentrada.setText(rs.getString(4));
             labelasientov.setText(rs.getString(5));
             labelasientoi.setText(rs.getString(5));
             labelbusv.setText(rs.getString(6));
             labelbusi.setText(rs.getString(6));
             labelusuario.setText(Usuario);
            }                                
        }
        catch(Exception ex) {        
         JOptionPane.showMessageDialog(null, "Error al obtener la inscripcion" + ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelfirma = new javax.swing.JLabel();
        labelnombre = new javax.swing.JLabel();
        labelcarne = new javax.swing.JLabel();
        labelentrada = new javax.swing.JLabel();
        labelprecio = new javax.swing.JLabel();
        labelasientoi = new javax.swing.JLabel();
        labelasientov = new javax.swing.JLabel();
        labelbusi = new javax.swing.JLabel();
        labelbusv = new javax.swing.JLabel();
        labelusuario = new javax.swing.JLabel();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 388));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        labelfirma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelfirma.setText("firma");
        jPanel1.add(labelfirma);
        labelfirma.setBounds(550, 130, 140, 22);

        labelnombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelnombre.setText("Nombre");
        jPanel1.add(labelnombre);
        labelnombre.setBounds(230, 160, 460, 22);

        labelcarne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelcarne.setText("Carne");
        jPanel1.add(labelcarne);
        labelcarne.setBounds(230, 200, 200, 22);

        labelentrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelentrada.setForeground(new java.awt.Color(255, 255, 255));
        labelentrada.setText("entrada");
        jPanel1.add(labelentrada);
        labelentrada.setBounds(90, 340, 120, 29);

        labelprecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelprecio.setText("Precio");
        jPanel1.add(labelprecio);
        labelprecio.setBounds(570, 200, 80, 22);

        labelasientoi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelasientoi.setForeground(new java.awt.Color(255, 255, 255));
        labelasientoi.setText("1");
        jPanel1.add(labelasientoi);
        labelasientoi.setBounds(650, 330, 30, 40);

        labelasientov.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelasientov.setForeground(new java.awt.Color(255, 255, 255));
        labelasientov.setText("1");
        jPanel1.add(labelasientov);
        labelasientov.setBounds(400, 330, 30, 40);

        labelbusi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelbusi.setForeground(new java.awt.Color(255, 255, 255));
        labelbusi.setText("1");
        jPanel1.add(labelbusi);
        labelbusi.setBounds(570, 330, 30, 40);

        labelbusv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelbusv.setForeground(new java.awt.Color(255, 255, 255));
        labelbusv.setText("1");
        jPanel1.add(labelbusv);
        labelbusv.setBounds(330, 330, 30, 40);

        labelusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelusuario.setText("usuario");
        jPanel1.add(labelusuario);
        labelusuario.setBounds(130, 230, 160, 22);

        labelfondo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/REcivo.jpg"))); // NOI18N
        jPanel1.add(labelfondo);
        labelfondo.setBounds(30, 0, 711, 412);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 854);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImprimirRecibo dialog = new ImprimirRecibo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelasientoi;
    private javax.swing.JLabel labelasientov;
    private javax.swing.JLabel labelbusi;
    private javax.swing.JLabel labelbusv;
    private javax.swing.JLabel labelcarne;
    private javax.swing.JLabel labelentrada;
    private javax.swing.JLabel labelfirma;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labelprecio;
    private javax.swing.JLabel labelusuario;
    // End of variables declaration//GEN-END:variables

    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException{
        if (pageIndex > 0) return NO_SUCH_PAGE;
        Graphics2D g2d = (Graphics2D)graphics;
        g2d.translate(pageFormat.getImageableX()+10, pageFormat.getImageableX()+10);
        g2d.scale(0.80, 0.80);
        jPanel1.printAll(graphics);
            return PAGE_EXISTS;
    }
    
    
}
